FROM python:3.8-slim

# Install streamlit and mlflow
RUN pip install --no-cache-dir streamlit mlflow

EXPOSE 5000

# Command to start the MLflow server with correct paths
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "/mlruns", "--default-artifact-root", "/models"]