# Use a Python base image to install MLflow
FROM python:3.8-slim

# Install dependencies including MLflow
RUN pip install --no-cache-dir mlflow

# Expose the port for MLflow UI
EXPOSE 5000

# Command to start the MLflow server with correct paths
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "/mlruns", "--default-artifact-root", "/models"]
